//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDictService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WordLookupReq", Namespace="http://schemas.datacontract.org/2004/07/SimpleDictService")]
    public partial class WordLookupReq : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string WordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Word
        {
            get
            {
                return this.WordField;
            }
            set
            {
                this.WordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WordLookupResp", Namespace="http://schemas.datacontract.org/2004/07/SimpleDictService")]
    public partial class WordLookupResp : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DefinitionField;
        
        private bool ExistsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Definition
        {
            get
            {
                return this.DefinitionField;
            }
            set
            {
                this.DefinitionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exists
        {
            get
            {
                return this.ExistsField;
            }
            set
            {
                this.ExistsField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITheServiceContract")]
public interface ITheServiceContract
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheServiceContract/WordLookup", ReplyAction="http://tempuri.org/ITheServiceContract/WordLookupResponse")]
    SimpleDictService.WordLookupResp WordLookup(SimpleDictService.WordLookupReq Request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITheServiceContractChannel : ITheServiceContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TheServiceContractClient : System.ServiceModel.ClientBase<ITheServiceContract>, ITheServiceContract
{
    
    public TheServiceContractClient()
    {
    }
    
    public TheServiceContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TheServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TheServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TheServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public SimpleDictService.WordLookupResp WordLookup(SimpleDictService.WordLookupReq Request)
    {
        return base.Channel.WordLookup(Request);
    }
}
