//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayServiceClient.HolidayServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", ConfigurationName="HolidayServiceReference.HolidayService2Soap")]
    public interface HolidayService2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/GetCountriesAvailable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        CountryCode[] GetCountriesAvailable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/GetHolidaysAvailable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayCode[] GetHolidaysAvailable(HolidayServiceClient.HolidayServiceReference.Country countryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/GetHolidayDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        System.DateTime GetHolidayDate(HolidayServiceClient.HolidayServiceReference.Country countryCode, string holidayCode, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/GetHolidaysForDateRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        Holiday[] GetHolidaysForDateRange(HolidayServiceClient.HolidayServiceReference.Country countryCode, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/GetHolidaysForYear", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        Holiday[] GetHolidaysForYear(HolidayServiceClient.HolidayServiceReference.Country countryCode, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/GetHolidaysForMonth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        Holiday[] GetHolidaysForMonth(HolidayServiceClient.HolidayServiceReference.Country countryCode, int year, int month);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/")]
    public partial class CountryCode : CodeDescriptionBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegionCode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HolidayCode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryCode))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/")]
    public abstract partial class CodeDescriptionBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/")]
    public partial class Holiday : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Country countryField;
        
        private string holidayCodeField;
        
        private string descriptorField;
        
        private HolidayType holidayTypeField;
        
        private HolidayDateType dateTypeField;
        
        private BankHoliday bankHolidayField;
        
        private System.DateTime dateField;
        
        private string relatedHolidayCodeField;
        
        private RegionCode[] applicableRegionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Country Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HolidayCode {
            get {
                return this.holidayCodeField;
            }
            set {
                this.holidayCodeField = value;
                this.RaisePropertyChanged("HolidayCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
                this.RaisePropertyChanged("Descriptor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public HolidayType HolidayType {
            get {
                return this.holidayTypeField;
            }
            set {
                this.holidayTypeField = value;
                this.RaisePropertyChanged("HolidayType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public HolidayDateType DateType {
            get {
                return this.dateTypeField;
            }
            set {
                this.dateTypeField = value;
                this.RaisePropertyChanged("DateType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public BankHoliday BankHoliday {
            get {
                return this.bankHolidayField;
            }
            set {
                this.bankHolidayField = value;
                this.RaisePropertyChanged("BankHoliday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RelatedHolidayCode {
            get {
                return this.relatedHolidayCodeField;
            }
            set {
                this.relatedHolidayCodeField = value;
                this.RaisePropertyChanged("RelatedHolidayCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public RegionCode[] ApplicableRegions {
            get {
                return this.applicableRegionsField;
            }
            set {
                this.applicableRegionsField = value;
                this.RaisePropertyChanged("ApplicableRegions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/")]
    public enum Country {
        
        /// <remarks/>
        Canada,
        
        /// <remarks/>
        GreatBritain,
        
        /// <remarks/>
        IrelandNorthern,
        
        /// <remarks/>
        IrelandRepublicOf,
        
        /// <remarks/>
        Scotland,
        
        /// <remarks/>
        UnitedStates,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/")]
    public enum HolidayType {
        
        /// <remarks/>
        Notable,
        
        /// <remarks/>
        Religious,
        
        /// <remarks/>
        NotableReligious,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/")]
    public enum HolidayDateType {
        
        /// <remarks/>
        Observed,
        
        /// <remarks/>
        Actual,
        
        /// <remarks/>
        ObservedActual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/")]
    public enum BankHoliday {
        
        /// <remarks/>
        Recognized,
        
        /// <remarks/>
        NotRecognized,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/")]
    public partial class RegionCode : CodeDescriptionBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/")]
    public partial class HolidayCode : CodeDescriptionBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HolidayService2SoapChannel : HolidayServiceClient.HolidayServiceReference.HolidayService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolidayService2SoapClient : System.ServiceModel.ClientBase<HolidayServiceClient.HolidayServiceReference.HolidayService2Soap>, HolidayServiceClient.HolidayServiceReference.HolidayService2Soap {
        
        public HolidayService2SoapClient() {
        }
        
        public HolidayService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolidayService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CountryCode[] GetCountriesAvailable() {
            return base.Channel.GetCountriesAvailable();
        }
        
        public HolidayCode[] GetHolidaysAvailable(HolidayServiceClient.HolidayServiceReference.Country countryCode) {
            return base.Channel.GetHolidaysAvailable(countryCode);
        }
        
        public System.DateTime GetHolidayDate(HolidayServiceClient.HolidayServiceReference.Country countryCode, string holidayCode, int year) {
            return base.Channel.GetHolidayDate(countryCode, holidayCode, year);
        }
        
        public Holiday[] GetHolidaysForDateRange(HolidayServiceClient.HolidayServiceReference.Country countryCode, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetHolidaysForDateRange(countryCode, startDate, endDate);
        }
        
        public Holiday[] GetHolidaysForYear(HolidayServiceClient.HolidayServiceReference.Country countryCode, int year) {
            return base.Channel.GetHolidaysForYear(countryCode, year);
        }
        
        public Holiday[] GetHolidaysForMonth(HolidayServiceClient.HolidayServiceReference.Country countryCode, int year, int month) {
            return base.Channel.GetHolidaysForMonth(countryCode, year, month);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", ConfigurationName="HolidayServiceReference.HolidayService2HttpGet")]
    public interface HolidayService2HttpGet {
        
        // CODEGEN: Generating message contract since the operation GetCountriesAvailable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetCoun" +
            "triesAvailableRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetCoun" +
            "triesAvailableResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableResponse GetCountriesAvailable(HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableRequest request);
        
        // CODEGEN: Generating message contract since the operation GetHolidaysAvailable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetHoli" +
            "daysAvailableRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetHoli" +
            "daysAvailableResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableResponse GetHolidaysAvailable(HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableRequest request);
        
        // CODEGEN: Generating message contract since the operation GetHolidayDate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetHoli" +
            "dayDateRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetHoli" +
            "dayDateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetHolidayDateResponse GetHolidayDate(HolidayServiceClient.HolidayServiceReference.GetHolidayDateRequest request);
        
        // CODEGEN: Generating message contract since the operation GetHolidaysForDateRange is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetHoli" +
            "daysForDateRangeRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetHoli" +
            "daysForDateRangeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeResponse GetHolidaysForDateRange(HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeRequest request);
        
        // CODEGEN: Generating message contract since the operation GetHolidaysForYear is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetHoli" +
            "daysForYearRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetHoli" +
            "daysForYearResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearResponse GetHolidaysForYear(HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearRequest request);
        
        // CODEGEN: Generating message contract since the operation GetHolidaysForMonth is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetHoli" +
            "daysForMonthRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpGet/GetHoli" +
            "daysForMonthResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthResponse GetHolidaysForMonth(HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesAvailableRequest {
        
        public GetCountriesAvailableRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesAvailableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CountryCode[] ArrayOfCountryCode;
        
        public GetCountriesAvailableResponse() {
        }
        
        public GetCountriesAvailableResponse(CountryCode[] ArrayOfCountryCode) {
            this.ArrayOfCountryCode = ArrayOfCountryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysAvailableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string countryCode;
        
        public GetHolidaysAvailableRequest() {
        }
        
        public GetHolidaysAvailableRequest(string countryCode) {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysAvailableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public HolidayCode[] ArrayOfHolidayCode;
        
        public GetHolidaysAvailableResponse() {
        }
        
        public GetHolidaysAvailableResponse(HolidayCode[] ArrayOfHolidayCode) {
            this.ArrayOfHolidayCode = ArrayOfHolidayCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidayDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string holidayCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string year;
        
        public GetHolidayDateRequest() {
        }
        
        public GetHolidayDateRequest(string countryCode, string holidayCode, string year) {
            this.countryCode = countryCode;
            this.holidayCode = holidayCode;
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidayDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        public System.DateTime dateTime;
        
        public GetHolidayDateResponse() {
        }
        
        public GetHolidayDateResponse(System.DateTime dateTime) {
            this.dateTime = dateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForDateRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string endDate;
        
        public GetHolidaysForDateRangeRequest() {
        }
        
        public GetHolidaysForDateRangeRequest(string countryCode, string startDate, string endDate) {
            this.countryCode = countryCode;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForDateRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Holiday[] ArrayOfHoliday;
        
        public GetHolidaysForDateRangeResponse() {
        }
        
        public GetHolidaysForDateRangeResponse(Holiday[] ArrayOfHoliday) {
            this.ArrayOfHoliday = ArrayOfHoliday;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForYearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string year;
        
        public GetHolidaysForYearRequest() {
        }
        
        public GetHolidaysForYearRequest(string countryCode, string year) {
            this.countryCode = countryCode;
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForYearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Holiday[] ArrayOfHoliday;
        
        public GetHolidaysForYearResponse() {
        }
        
        public GetHolidaysForYearResponse(Holiday[] ArrayOfHoliday) {
            this.ArrayOfHoliday = ArrayOfHoliday;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForMonthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string month;
        
        public GetHolidaysForMonthRequest() {
        }
        
        public GetHolidaysForMonthRequest(string countryCode, string year, string month) {
            this.countryCode = countryCode;
            this.year = year;
            this.month = month;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForMonthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Holiday[] ArrayOfHoliday;
        
        public GetHolidaysForMonthResponse() {
        }
        
        public GetHolidaysForMonthResponse(Holiday[] ArrayOfHoliday) {
            this.ArrayOfHoliday = ArrayOfHoliday;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HolidayService2HttpGetChannel : HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolidayService2HttpGetClient : System.ServiceModel.ClientBase<HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet>, HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet {
        
        public HolidayService2HttpGetClient() {
        }
        
        public HolidayService2HttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolidayService2HttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayService2HttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayService2HttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableResponse HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet.GetCountriesAvailable(HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableRequest request) {
            return base.Channel.GetCountriesAvailable(request);
        }
        
        public CountryCode[] GetCountriesAvailable() {
            HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableRequest inValue = new HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableRequest();
            HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableResponse retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet)(this)).GetCountriesAvailable(inValue);
            return retVal.ArrayOfCountryCode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableResponse HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet.GetHolidaysAvailable(HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableRequest request) {
            return base.Channel.GetHolidaysAvailable(request);
        }
        
        public HolidayCode[] GetHolidaysAvailable(string countryCode) {
            HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableRequest inValue = new HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableRequest();
            inValue.countryCode = countryCode;
            HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableResponse retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet)(this)).GetHolidaysAvailable(inValue);
            return retVal.ArrayOfHolidayCode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetHolidayDateResponse HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet.GetHolidayDate(HolidayServiceClient.HolidayServiceReference.GetHolidayDateRequest request) {
            return base.Channel.GetHolidayDate(request);
        }
        
        public System.DateTime GetHolidayDate(string countryCode, string holidayCode, string year) {
            HolidayServiceClient.HolidayServiceReference.GetHolidayDateRequest inValue = new HolidayServiceClient.HolidayServiceReference.GetHolidayDateRequest();
            inValue.countryCode = countryCode;
            inValue.holidayCode = holidayCode;
            inValue.year = year;
            HolidayServiceClient.HolidayServiceReference.GetHolidayDateResponse retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet)(this)).GetHolidayDate(inValue);
            return retVal.dateTime;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeResponse HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet.GetHolidaysForDateRange(HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeRequest request) {
            return base.Channel.GetHolidaysForDateRange(request);
        }
        
        public Holiday[] GetHolidaysForDateRange(string countryCode, string startDate, string endDate) {
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeRequest inValue = new HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeRequest();
            inValue.countryCode = countryCode;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeResponse retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet)(this)).GetHolidaysForDateRange(inValue);
            return retVal.ArrayOfHoliday;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearResponse HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet.GetHolidaysForYear(HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearRequest request) {
            return base.Channel.GetHolidaysForYear(request);
        }
        
        public Holiday[] GetHolidaysForYear(string countryCode, string year) {
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearRequest inValue = new HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearRequest();
            inValue.countryCode = countryCode;
            inValue.year = year;
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearResponse retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet)(this)).GetHolidaysForYear(inValue);
            return retVal.ArrayOfHoliday;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthResponse HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet.GetHolidaysForMonth(HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthRequest request) {
            return base.Channel.GetHolidaysForMonth(request);
        }
        
        public Holiday[] GetHolidaysForMonth(string countryCode, string year, string month) {
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthRequest inValue = new HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthRequest();
            inValue.countryCode = countryCode;
            inValue.year = year;
            inValue.month = month;
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthResponse retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpGet)(this)).GetHolidaysForMonth(inValue);
            return retVal.ArrayOfHoliday;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", ConfigurationName="HolidayServiceReference.HolidayService2HttpPost")]
    public interface HolidayService2HttpPost {
        
        // CODEGEN: Generating message contract since the operation GetCountriesAvailable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetCou" +
            "ntriesAvailableRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetCou" +
            "ntriesAvailableResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableResponse1 GetCountriesAvailable(HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetHolidaysAvailable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetHol" +
            "idaysAvailableRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetHol" +
            "idaysAvailableResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableResponse1 GetHolidaysAvailable(HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetHolidayDate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetHol" +
            "idayDateRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetHol" +
            "idayDateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetHolidayDateResponse1 GetHolidayDate(HolidayServiceClient.HolidayServiceReference.GetHolidayDateRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetHolidaysForDateRange is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetHol" +
            "idaysForDateRangeRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetHol" +
            "idaysForDateRangeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeResponse1 GetHolidaysForDateRange(HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetHolidaysForYear is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetHol" +
            "idaysForYearRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetHol" +
            "idaysForYearResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearResponse1 GetHolidaysForYear(HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetHolidaysForMonth is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetHol" +
            "idaysForMonthRequest", ReplyAction="http://www.holidaywebservice.com/HolidayService_v2/HolidayService2HttpPost/GetHol" +
            "idaysForMonthResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CodeDescriptionBase))]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthResponse1 GetHolidaysForMonth(HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesAvailableRequest1 {
        
        public GetCountriesAvailableRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesAvailableResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CountryCode[] ArrayOfCountryCode;
        
        public GetCountriesAvailableResponse1() {
        }
        
        public GetCountriesAvailableResponse1(CountryCode[] ArrayOfCountryCode) {
            this.ArrayOfCountryCode = ArrayOfCountryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysAvailableRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string countryCode;
        
        public GetHolidaysAvailableRequest1() {
        }
        
        public GetHolidaysAvailableRequest1(string countryCode) {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysAvailableResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public HolidayCode[] ArrayOfHolidayCode;
        
        public GetHolidaysAvailableResponse1() {
        }
        
        public GetHolidaysAvailableResponse1(HolidayCode[] ArrayOfHolidayCode) {
            this.ArrayOfHolidayCode = ArrayOfHolidayCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidayDateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string holidayCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string year;
        
        public GetHolidayDateRequest1() {
        }
        
        public GetHolidayDateRequest1(string countryCode, string holidayCode, string year) {
            this.countryCode = countryCode;
            this.holidayCode = holidayCode;
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidayDateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        public System.DateTime dateTime;
        
        public GetHolidayDateResponse1() {
        }
        
        public GetHolidayDateResponse1(System.DateTime dateTime) {
            this.dateTime = dateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForDateRangeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string endDate;
        
        public GetHolidaysForDateRangeRequest1() {
        }
        
        public GetHolidaysForDateRangeRequest1(string countryCode, string startDate, string endDate) {
            this.countryCode = countryCode;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForDateRangeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Holiday[] ArrayOfHoliday;
        
        public GetHolidaysForDateRangeResponse1() {
        }
        
        public GetHolidaysForDateRangeResponse1(Holiday[] ArrayOfHoliday) {
            this.ArrayOfHoliday = ArrayOfHoliday;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForYearRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string year;
        
        public GetHolidaysForYearRequest1() {
        }
        
        public GetHolidaysForYearRequest1(string countryCode, string year) {
            this.countryCode = countryCode;
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForYearResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Holiday[] ArrayOfHoliday;
        
        public GetHolidaysForYearResponse1() {
        }
        
        public GetHolidaysForYearResponse1(Holiday[] ArrayOfHoliday) {
            this.ArrayOfHoliday = ArrayOfHoliday;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForMonthRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string month;
        
        public GetHolidaysForMonthRequest1() {
        }
        
        public GetHolidaysForMonthRequest1(string countryCode, string year, string month) {
            this.countryCode = countryCode;
            this.year = year;
            this.month = month;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHolidaysForMonthResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.holidaywebservice.com/HolidayService_v2/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Holiday[] ArrayOfHoliday;
        
        public GetHolidaysForMonthResponse1() {
        }
        
        public GetHolidaysForMonthResponse1(Holiday[] ArrayOfHoliday) {
            this.ArrayOfHoliday = ArrayOfHoliday;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HolidayService2HttpPostChannel : HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolidayService2HttpPostClient : System.ServiceModel.ClientBase<HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost>, HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost {
        
        public HolidayService2HttpPostClient() {
        }
        
        public HolidayService2HttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolidayService2HttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayService2HttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayService2HttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableResponse1 HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost.GetCountriesAvailable(HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableRequest1 request) {
            return base.Channel.GetCountriesAvailable(request);
        }
        
        public CountryCode[] GetCountriesAvailable() {
            HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableRequest1 inValue = new HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableRequest1();
            HolidayServiceClient.HolidayServiceReference.GetCountriesAvailableResponse1 retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost)(this)).GetCountriesAvailable(inValue);
            return retVal.ArrayOfCountryCode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableResponse1 HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost.GetHolidaysAvailable(HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableRequest1 request) {
            return base.Channel.GetHolidaysAvailable(request);
        }
        
        public HolidayCode[] GetHolidaysAvailable(string countryCode) {
            HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableRequest1 inValue = new HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableRequest1();
            inValue.countryCode = countryCode;
            HolidayServiceClient.HolidayServiceReference.GetHolidaysAvailableResponse1 retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost)(this)).GetHolidaysAvailable(inValue);
            return retVal.ArrayOfHolidayCode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetHolidayDateResponse1 HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost.GetHolidayDate(HolidayServiceClient.HolidayServiceReference.GetHolidayDateRequest1 request) {
            return base.Channel.GetHolidayDate(request);
        }
        
        public System.DateTime GetHolidayDate(string countryCode, string holidayCode, string year) {
            HolidayServiceClient.HolidayServiceReference.GetHolidayDateRequest1 inValue = new HolidayServiceClient.HolidayServiceReference.GetHolidayDateRequest1();
            inValue.countryCode = countryCode;
            inValue.holidayCode = holidayCode;
            inValue.year = year;
            HolidayServiceClient.HolidayServiceReference.GetHolidayDateResponse1 retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost)(this)).GetHolidayDate(inValue);
            return retVal.dateTime;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeResponse1 HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost.GetHolidaysForDateRange(HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeRequest1 request) {
            return base.Channel.GetHolidaysForDateRange(request);
        }
        
        public Holiday[] GetHolidaysForDateRange(string countryCode, string startDate, string endDate) {
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeRequest1 inValue = new HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeRequest1();
            inValue.countryCode = countryCode;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForDateRangeResponse1 retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost)(this)).GetHolidaysForDateRange(inValue);
            return retVal.ArrayOfHoliday;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearResponse1 HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost.GetHolidaysForYear(HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearRequest1 request) {
            return base.Channel.GetHolidaysForYear(request);
        }
        
        public Holiday[] GetHolidaysForYear(string countryCode, string year) {
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearRequest1 inValue = new HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearRequest1();
            inValue.countryCode = countryCode;
            inValue.year = year;
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForYearResponse1 retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost)(this)).GetHolidaysForYear(inValue);
            return retVal.ArrayOfHoliday;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthResponse1 HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost.GetHolidaysForMonth(HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthRequest1 request) {
            return base.Channel.GetHolidaysForMonth(request);
        }
        
        public Holiday[] GetHolidaysForMonth(string countryCode, string year, string month) {
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthRequest1 inValue = new HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthRequest1();
            inValue.countryCode = countryCode;
            inValue.year = year;
            inValue.month = month;
            HolidayServiceClient.HolidayServiceReference.GetHolidaysForMonthResponse1 retVal = ((HolidayServiceClient.HolidayServiceReference.HolidayService2HttpPost)(this)).GetHolidaysForMonth(inValue);
            return retVal.ArrayOfHoliday;
        }
    }
}
