//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AonawareDictClient.DictServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.aonaware.com/webservices/", ConfigurationName="DictServiceReference.DictServiceSoap")]
    public interface DictServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/ServerInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServerInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictionaryList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dictionary[] DictionaryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictionaryListExtended", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dictionary[] DictionaryListExtended();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictionaryInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DictionaryInfo(string dictId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/Define", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.WordDefinition Define(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DefineInDict", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.WordDefinition DefineInDict(string dictId, string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/StrategyList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Strategy[] StrategyList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/Match", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DictionaryWord[] Match(string word, string strategy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/MatchInDict", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DictionaryWord[] MatchInDict(string dictId, string word, string strategy);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.aonaware.com/webservices/")]
    public partial class Dictionary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.aonaware.com/webservices/")]
    public partial class DictionaryWord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dictionaryIdField;
        
        private string wordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DictionaryId {
            get {
                return this.dictionaryIdField;
            }
            set {
                this.dictionaryIdField = value;
                this.RaisePropertyChanged("DictionaryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
                this.RaisePropertyChanged("Word");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.aonaware.com/webservices/")]
    public partial class Strategy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.aonaware.com/webservices/")]
    public partial class Definition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wordField;
        
        private Dictionary dictionaryField;
        
        private string wordDefinitionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
                this.RaisePropertyChanged("Word");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Dictionary Dictionary {
            get {
                return this.dictionaryField;
            }
            set {
                this.dictionaryField = value;
                this.RaisePropertyChanged("Dictionary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string WordDefinition {
            get {
                return this.wordDefinitionField;
            }
            set {
                this.wordDefinitionField = value;
                this.RaisePropertyChanged("WordDefinition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.aonaware.com/webservices/")]
    public partial class WordDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wordField;
        
        private Definition[] definitionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
                this.RaisePropertyChanged("Word");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Definition[] Definitions {
            get {
                return this.definitionsField;
            }
            set {
                this.definitionsField = value;
                this.RaisePropertyChanged("Definitions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DictServiceSoapChannel : AonawareDictClient.DictServiceReference.DictServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DictServiceSoapClient : System.ServiceModel.ClientBase<AonawareDictClient.DictServiceReference.DictServiceSoap>, AonawareDictClient.DictServiceReference.DictServiceSoap {
        
        public DictServiceSoapClient() {
        }
        
        public DictServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DictServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ServerInfo() {
            return base.Channel.ServerInfo();
        }
        
        public Dictionary[] DictionaryList() {
            return base.Channel.DictionaryList();
        }
        
        public Dictionary[] DictionaryListExtended() {
            return base.Channel.DictionaryListExtended();
        }
        
        public string DictionaryInfo(string dictId) {
            return base.Channel.DictionaryInfo(dictId);
        }
        
        public AonawareDictClient.DictServiceReference.WordDefinition Define(string word) {
            return base.Channel.Define(word);
        }
        
        public AonawareDictClient.DictServiceReference.WordDefinition DefineInDict(string dictId, string word) {
            return base.Channel.DefineInDict(dictId, word);
        }
        
        public Strategy[] StrategyList() {
            return base.Channel.StrategyList();
        }
        
        public DictionaryWord[] Match(string word, string strategy) {
            return base.Channel.Match(word, strategy);
        }
        
        public DictionaryWord[] MatchInDict(string dictId, string word, string strategy) {
            return base.Channel.MatchInDict(dictId, word, strategy);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.aonaware.com/webservices/", ConfigurationName="DictServiceReference.DictServiceHttpGet")]
    public interface DictServiceHttpGet {
        
        // CODEGEN: Generating message contract since the operation ServerInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpGet/ServerInfoRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpGet/ServerInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.ServerInfoResponse ServerInfo(AonawareDictClient.DictServiceReference.ServerInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation DictionaryList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpGet/DictionaryListRequest" +
            "", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpGet/DictionaryListRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.DictionaryListResponse DictionaryList(AonawareDictClient.DictServiceReference.DictionaryListRequest request);
        
        // CODEGEN: Generating message contract since the operation DictionaryListExtended is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpGet/DictionaryListExtende" +
            "dRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpGet/DictionaryListExtende" +
            "dResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.DictionaryListExtendedResponse DictionaryListExtended(AonawareDictClient.DictServiceReference.DictionaryListExtendedRequest request);
        
        // CODEGEN: Generating message contract since the operation DictionaryInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpGet/DictionaryInfoRequest" +
            "", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpGet/DictionaryInfoRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.DictionaryInfoResponse DictionaryInfo(AonawareDictClient.DictServiceReference.DictionaryInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation Define is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpGet/DefineRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpGet/DefineResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.DefineResponse Define(AonawareDictClient.DictServiceReference.DefineRequest request);
        
        // CODEGEN: Generating message contract since the operation DefineInDict is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpGet/DefineInDictRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpGet/DefineInDictResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.DefineInDictResponse DefineInDict(AonawareDictClient.DictServiceReference.DefineInDictRequest request);
        
        // CODEGEN: Generating message contract since the operation StrategyList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpGet/StrategyListRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpGet/StrategyListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.StrategyListResponse StrategyList(AonawareDictClient.DictServiceReference.StrategyListRequest request);
        
        // CODEGEN: Generating message contract since the operation Match is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpGet/MatchRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpGet/MatchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.MatchResponse Match(AonawareDictClient.DictServiceReference.MatchRequest request);
        
        // CODEGEN: Generating message contract since the operation MatchInDict is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpGet/MatchInDictRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpGet/MatchInDictResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.MatchInDictResponse MatchInDict(AonawareDictClient.DictServiceReference.MatchInDictRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServerInfoRequest {
        
        public ServerInfoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public ServerInfoResponse() {
        }
        
        public ServerInfoResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryListRequest {
        
        public DictionaryListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Dictionary[] ArrayOfDictionary;
        
        public DictionaryListResponse() {
        }
        
        public DictionaryListResponse(Dictionary[] ArrayOfDictionary) {
            this.ArrayOfDictionary = ArrayOfDictionary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryListExtendedRequest {
        
        public DictionaryListExtendedRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryListExtendedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Dictionary[] ArrayOfDictionary;
        
        public DictionaryListExtendedResponse() {
        }
        
        public DictionaryListExtendedResponse(Dictionary[] ArrayOfDictionary) {
            this.ArrayOfDictionary = ArrayOfDictionary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string dictId;
        
        public DictionaryInfoRequest() {
        }
        
        public DictionaryInfoRequest(string dictId) {
            this.dictId = dictId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public DictionaryInfoResponse() {
        }
        
        public DictionaryInfoResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string word;
        
        public DefineRequest() {
        }
        
        public DefineRequest(string word) {
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AonawareDictClient.DictServiceReference.WordDefinition WordDefinition;
        
        public DefineResponse() {
        }
        
        public DefineResponse(AonawareDictClient.DictServiceReference.WordDefinition WordDefinition) {
            this.WordDefinition = WordDefinition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefineInDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string dictId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string word;
        
        public DefineInDictRequest() {
        }
        
        public DefineInDictRequest(string dictId, string word) {
            this.dictId = dictId;
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefineInDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AonawareDictClient.DictServiceReference.WordDefinition WordDefinition;
        
        public DefineInDictResponse() {
        }
        
        public DefineInDictResponse(AonawareDictClient.DictServiceReference.WordDefinition WordDefinition) {
            this.WordDefinition = WordDefinition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrategyListRequest {
        
        public StrategyListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrategyListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Strategy[] ArrayOfStrategy;
        
        public StrategyListResponse() {
        }
        
        public StrategyListResponse(Strategy[] ArrayOfStrategy) {
            this.ArrayOfStrategy = ArrayOfStrategy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string word;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string strategy;
        
        public MatchRequest() {
        }
        
        public MatchRequest(string word, string strategy) {
            this.word = word;
            this.strategy = strategy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DictionaryWord[] ArrayOfDictionaryWord;
        
        public MatchResponse() {
        }
        
        public MatchResponse(DictionaryWord[] ArrayOfDictionaryWord) {
            this.ArrayOfDictionaryWord = ArrayOfDictionaryWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchInDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string dictId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string word;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string strategy;
        
        public MatchInDictRequest() {
        }
        
        public MatchInDictRequest(string dictId, string word, string strategy) {
            this.dictId = dictId;
            this.word = word;
            this.strategy = strategy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchInDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DictionaryWord[] ArrayOfDictionaryWord;
        
        public MatchInDictResponse() {
        }
        
        public MatchInDictResponse(DictionaryWord[] ArrayOfDictionaryWord) {
            this.ArrayOfDictionaryWord = ArrayOfDictionaryWord;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DictServiceHttpGetChannel : AonawareDictClient.DictServiceReference.DictServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DictServiceHttpGetClient : System.ServiceModel.ClientBase<AonawareDictClient.DictServiceReference.DictServiceHttpGet>, AonawareDictClient.DictServiceReference.DictServiceHttpGet {
        
        public DictServiceHttpGetClient() {
        }
        
        public DictServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DictServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.ServerInfoResponse AonawareDictClient.DictServiceReference.DictServiceHttpGet.ServerInfo(AonawareDictClient.DictServiceReference.ServerInfoRequest request) {
            return base.Channel.ServerInfo(request);
        }
        
        public string ServerInfo() {
            AonawareDictClient.DictServiceReference.ServerInfoRequest inValue = new AonawareDictClient.DictServiceReference.ServerInfoRequest();
            AonawareDictClient.DictServiceReference.ServerInfoResponse retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpGet)(this)).ServerInfo(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.DictionaryListResponse AonawareDictClient.DictServiceReference.DictServiceHttpGet.DictionaryList(AonawareDictClient.DictServiceReference.DictionaryListRequest request) {
            return base.Channel.DictionaryList(request);
        }
        
        public Dictionary[] DictionaryList() {
            AonawareDictClient.DictServiceReference.DictionaryListRequest inValue = new AonawareDictClient.DictServiceReference.DictionaryListRequest();
            AonawareDictClient.DictServiceReference.DictionaryListResponse retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpGet)(this)).DictionaryList(inValue);
            return retVal.ArrayOfDictionary;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.DictionaryListExtendedResponse AonawareDictClient.DictServiceReference.DictServiceHttpGet.DictionaryListExtended(AonawareDictClient.DictServiceReference.DictionaryListExtendedRequest request) {
            return base.Channel.DictionaryListExtended(request);
        }
        
        public Dictionary[] DictionaryListExtended() {
            AonawareDictClient.DictServiceReference.DictionaryListExtendedRequest inValue = new AonawareDictClient.DictServiceReference.DictionaryListExtendedRequest();
            AonawareDictClient.DictServiceReference.DictionaryListExtendedResponse retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpGet)(this)).DictionaryListExtended(inValue);
            return retVal.ArrayOfDictionary;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.DictionaryInfoResponse AonawareDictClient.DictServiceReference.DictServiceHttpGet.DictionaryInfo(AonawareDictClient.DictServiceReference.DictionaryInfoRequest request) {
            return base.Channel.DictionaryInfo(request);
        }
        
        public string DictionaryInfo(string dictId) {
            AonawareDictClient.DictServiceReference.DictionaryInfoRequest inValue = new AonawareDictClient.DictServiceReference.DictionaryInfoRequest();
            inValue.dictId = dictId;
            AonawareDictClient.DictServiceReference.DictionaryInfoResponse retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpGet)(this)).DictionaryInfo(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.DefineResponse AonawareDictClient.DictServiceReference.DictServiceHttpGet.Define(AonawareDictClient.DictServiceReference.DefineRequest request) {
            return base.Channel.Define(request);
        }
        
        public AonawareDictClient.DictServiceReference.WordDefinition Define(string word) {
            AonawareDictClient.DictServiceReference.DefineRequest inValue = new AonawareDictClient.DictServiceReference.DefineRequest();
            inValue.word = word;
            AonawareDictClient.DictServiceReference.DefineResponse retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpGet)(this)).Define(inValue);
            return retVal.WordDefinition;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.DefineInDictResponse AonawareDictClient.DictServiceReference.DictServiceHttpGet.DefineInDict(AonawareDictClient.DictServiceReference.DefineInDictRequest request) {
            return base.Channel.DefineInDict(request);
        }
        
        public AonawareDictClient.DictServiceReference.WordDefinition DefineInDict(string dictId, string word) {
            AonawareDictClient.DictServiceReference.DefineInDictRequest inValue = new AonawareDictClient.DictServiceReference.DefineInDictRequest();
            inValue.dictId = dictId;
            inValue.word = word;
            AonawareDictClient.DictServiceReference.DefineInDictResponse retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpGet)(this)).DefineInDict(inValue);
            return retVal.WordDefinition;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.StrategyListResponse AonawareDictClient.DictServiceReference.DictServiceHttpGet.StrategyList(AonawareDictClient.DictServiceReference.StrategyListRequest request) {
            return base.Channel.StrategyList(request);
        }
        
        public Strategy[] StrategyList() {
            AonawareDictClient.DictServiceReference.StrategyListRequest inValue = new AonawareDictClient.DictServiceReference.StrategyListRequest();
            AonawareDictClient.DictServiceReference.StrategyListResponse retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpGet)(this)).StrategyList(inValue);
            return retVal.ArrayOfStrategy;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.MatchResponse AonawareDictClient.DictServiceReference.DictServiceHttpGet.Match(AonawareDictClient.DictServiceReference.MatchRequest request) {
            return base.Channel.Match(request);
        }
        
        public DictionaryWord[] Match(string word, string strategy) {
            AonawareDictClient.DictServiceReference.MatchRequest inValue = new AonawareDictClient.DictServiceReference.MatchRequest();
            inValue.word = word;
            inValue.strategy = strategy;
            AonawareDictClient.DictServiceReference.MatchResponse retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpGet)(this)).Match(inValue);
            return retVal.ArrayOfDictionaryWord;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.MatchInDictResponse AonawareDictClient.DictServiceReference.DictServiceHttpGet.MatchInDict(AonawareDictClient.DictServiceReference.MatchInDictRequest request) {
            return base.Channel.MatchInDict(request);
        }
        
        public DictionaryWord[] MatchInDict(string dictId, string word, string strategy) {
            AonawareDictClient.DictServiceReference.MatchInDictRequest inValue = new AonawareDictClient.DictServiceReference.MatchInDictRequest();
            inValue.dictId = dictId;
            inValue.word = word;
            inValue.strategy = strategy;
            AonawareDictClient.DictServiceReference.MatchInDictResponse retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpGet)(this)).MatchInDict(inValue);
            return retVal.ArrayOfDictionaryWord;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.aonaware.com/webservices/", ConfigurationName="DictServiceReference.DictServiceHttpPost")]
    public interface DictServiceHttpPost {
        
        // CODEGEN: Generating message contract since the operation ServerInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpPost/ServerInfoRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpPost/ServerInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.ServerInfoResponse1 ServerInfo(AonawareDictClient.DictServiceReference.ServerInfoRequest1 request);
        
        // CODEGEN: Generating message contract since the operation DictionaryList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpPost/DictionaryListReques" +
            "t", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpPost/DictionaryListRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.DictionaryListResponse1 DictionaryList(AonawareDictClient.DictServiceReference.DictionaryListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation DictionaryListExtended is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpPost/DictionaryListExtend" +
            "edRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpPost/DictionaryListExtend" +
            "edResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.DictionaryListExtendedResponse1 DictionaryListExtended(AonawareDictClient.DictServiceReference.DictionaryListExtendedRequest1 request);
        
        // CODEGEN: Generating message contract since the operation DictionaryInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpPost/DictionaryInfoReques" +
            "t", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpPost/DictionaryInfoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.DictionaryInfoResponse1 DictionaryInfo(AonawareDictClient.DictServiceReference.DictionaryInfoRequest1 request);
        
        // CODEGEN: Generating message contract since the operation Define is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpPost/DefineRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpPost/DefineResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.DefineResponse1 Define(AonawareDictClient.DictServiceReference.DefineRequest1 request);
        
        // CODEGEN: Generating message contract since the operation DefineInDict is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpPost/DefineInDictRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpPost/DefineInDictResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.DefineInDictResponse1 DefineInDict(AonawareDictClient.DictServiceReference.DefineInDictRequest1 request);
        
        // CODEGEN: Generating message contract since the operation StrategyList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpPost/StrategyListRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpPost/StrategyListResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.StrategyListResponse1 StrategyList(AonawareDictClient.DictServiceReference.StrategyListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation Match is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpPost/MatchRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpPost/MatchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.MatchResponse1 Match(AonawareDictClient.DictServiceReference.MatchRequest1 request);
        
        // CODEGEN: Generating message contract since the operation MatchInDict is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aonaware.com/webservices/DictServiceHttpPost/MatchInDictRequest", ReplyAction="http://services.aonaware.com/webservices/DictServiceHttpPost/MatchInDictResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AonawareDictClient.DictServiceReference.MatchInDictResponse1 MatchInDict(AonawareDictClient.DictServiceReference.MatchInDictRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServerInfoRequest1 {
        
        public ServerInfoRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServerInfoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public ServerInfoResponse1() {
        }
        
        public ServerInfoResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryListRequest1 {
        
        public DictionaryListRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Dictionary[] ArrayOfDictionary;
        
        public DictionaryListResponse1() {
        }
        
        public DictionaryListResponse1(Dictionary[] ArrayOfDictionary) {
            this.ArrayOfDictionary = ArrayOfDictionary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryListExtendedRequest1 {
        
        public DictionaryListExtendedRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryListExtendedResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Dictionary[] ArrayOfDictionary;
        
        public DictionaryListExtendedResponse1() {
        }
        
        public DictionaryListExtendedResponse1(Dictionary[] ArrayOfDictionary) {
            this.ArrayOfDictionary = ArrayOfDictionary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryInfoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string dictId;
        
        public DictionaryInfoRequest1() {
        }
        
        public DictionaryInfoRequest1(string dictId) {
            this.dictId = dictId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DictionaryInfoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public DictionaryInfoResponse1() {
        }
        
        public DictionaryInfoResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefineRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string word;
        
        public DefineRequest1() {
        }
        
        public DefineRequest1(string word) {
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefineResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AonawareDictClient.DictServiceReference.WordDefinition WordDefinition;
        
        public DefineResponse1() {
        }
        
        public DefineResponse1(AonawareDictClient.DictServiceReference.WordDefinition WordDefinition) {
            this.WordDefinition = WordDefinition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefineInDictRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string dictId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string word;
        
        public DefineInDictRequest1() {
        }
        
        public DefineInDictRequest1(string dictId, string word) {
            this.dictId = dictId;
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DefineInDictResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AonawareDictClient.DictServiceReference.WordDefinition WordDefinition;
        
        public DefineInDictResponse1() {
        }
        
        public DefineInDictResponse1(AonawareDictClient.DictServiceReference.WordDefinition WordDefinition) {
            this.WordDefinition = WordDefinition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrategyListRequest1 {
        
        public StrategyListRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrategyListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Strategy[] ArrayOfStrategy;
        
        public StrategyListResponse1() {
        }
        
        public StrategyListResponse1(Strategy[] ArrayOfStrategy) {
            this.ArrayOfStrategy = ArrayOfStrategy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string word;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string strategy;
        
        public MatchRequest1() {
        }
        
        public MatchRequest1(string word, string strategy) {
            this.word = word;
            this.strategy = strategy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DictionaryWord[] ArrayOfDictionaryWord;
        
        public MatchResponse1() {
        }
        
        public MatchResponse1(DictionaryWord[] ArrayOfDictionaryWord) {
            this.ArrayOfDictionaryWord = ArrayOfDictionaryWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchInDictRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string dictId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string word;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string strategy;
        
        public MatchInDictRequest1() {
        }
        
        public MatchInDictRequest1(string dictId, string word, string strategy) {
            this.dictId = dictId;
            this.word = word;
            this.strategy = strategy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MatchInDictResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aonaware.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DictionaryWord[] ArrayOfDictionaryWord;
        
        public MatchInDictResponse1() {
        }
        
        public MatchInDictResponse1(DictionaryWord[] ArrayOfDictionaryWord) {
            this.ArrayOfDictionaryWord = ArrayOfDictionaryWord;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DictServiceHttpPostChannel : AonawareDictClient.DictServiceReference.DictServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DictServiceHttpPostClient : System.ServiceModel.ClientBase<AonawareDictClient.DictServiceReference.DictServiceHttpPost>, AonawareDictClient.DictServiceReference.DictServiceHttpPost {
        
        public DictServiceHttpPostClient() {
        }
        
        public DictServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DictServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.ServerInfoResponse1 AonawareDictClient.DictServiceReference.DictServiceHttpPost.ServerInfo(AonawareDictClient.DictServiceReference.ServerInfoRequest1 request) {
            return base.Channel.ServerInfo(request);
        }
        
        public string ServerInfo() {
            AonawareDictClient.DictServiceReference.ServerInfoRequest1 inValue = new AonawareDictClient.DictServiceReference.ServerInfoRequest1();
            AonawareDictClient.DictServiceReference.ServerInfoResponse1 retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpPost)(this)).ServerInfo(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.DictionaryListResponse1 AonawareDictClient.DictServiceReference.DictServiceHttpPost.DictionaryList(AonawareDictClient.DictServiceReference.DictionaryListRequest1 request) {
            return base.Channel.DictionaryList(request);
        }
        
        public Dictionary[] DictionaryList() {
            AonawareDictClient.DictServiceReference.DictionaryListRequest1 inValue = new AonawareDictClient.DictServiceReference.DictionaryListRequest1();
            AonawareDictClient.DictServiceReference.DictionaryListResponse1 retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpPost)(this)).DictionaryList(inValue);
            return retVal.ArrayOfDictionary;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.DictionaryListExtendedResponse1 AonawareDictClient.DictServiceReference.DictServiceHttpPost.DictionaryListExtended(AonawareDictClient.DictServiceReference.DictionaryListExtendedRequest1 request) {
            return base.Channel.DictionaryListExtended(request);
        }
        
        public Dictionary[] DictionaryListExtended() {
            AonawareDictClient.DictServiceReference.DictionaryListExtendedRequest1 inValue = new AonawareDictClient.DictServiceReference.DictionaryListExtendedRequest1();
            AonawareDictClient.DictServiceReference.DictionaryListExtendedResponse1 retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpPost)(this)).DictionaryListExtended(inValue);
            return retVal.ArrayOfDictionary;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.DictionaryInfoResponse1 AonawareDictClient.DictServiceReference.DictServiceHttpPost.DictionaryInfo(AonawareDictClient.DictServiceReference.DictionaryInfoRequest1 request) {
            return base.Channel.DictionaryInfo(request);
        }
        
        public string DictionaryInfo(string dictId) {
            AonawareDictClient.DictServiceReference.DictionaryInfoRequest1 inValue = new AonawareDictClient.DictServiceReference.DictionaryInfoRequest1();
            inValue.dictId = dictId;
            AonawareDictClient.DictServiceReference.DictionaryInfoResponse1 retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpPost)(this)).DictionaryInfo(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.DefineResponse1 AonawareDictClient.DictServiceReference.DictServiceHttpPost.Define(AonawareDictClient.DictServiceReference.DefineRequest1 request) {
            return base.Channel.Define(request);
        }
        
        public AonawareDictClient.DictServiceReference.WordDefinition Define(string word) {
            AonawareDictClient.DictServiceReference.DefineRequest1 inValue = new AonawareDictClient.DictServiceReference.DefineRequest1();
            inValue.word = word;
            AonawareDictClient.DictServiceReference.DefineResponse1 retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpPost)(this)).Define(inValue);
            return retVal.WordDefinition;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.DefineInDictResponse1 AonawareDictClient.DictServiceReference.DictServiceHttpPost.DefineInDict(AonawareDictClient.DictServiceReference.DefineInDictRequest1 request) {
            return base.Channel.DefineInDict(request);
        }
        
        public AonawareDictClient.DictServiceReference.WordDefinition DefineInDict(string dictId, string word) {
            AonawareDictClient.DictServiceReference.DefineInDictRequest1 inValue = new AonawareDictClient.DictServiceReference.DefineInDictRequest1();
            inValue.dictId = dictId;
            inValue.word = word;
            AonawareDictClient.DictServiceReference.DefineInDictResponse1 retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpPost)(this)).DefineInDict(inValue);
            return retVal.WordDefinition;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.StrategyListResponse1 AonawareDictClient.DictServiceReference.DictServiceHttpPost.StrategyList(AonawareDictClient.DictServiceReference.StrategyListRequest1 request) {
            return base.Channel.StrategyList(request);
        }
        
        public Strategy[] StrategyList() {
            AonawareDictClient.DictServiceReference.StrategyListRequest1 inValue = new AonawareDictClient.DictServiceReference.StrategyListRequest1();
            AonawareDictClient.DictServiceReference.StrategyListResponse1 retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpPost)(this)).StrategyList(inValue);
            return retVal.ArrayOfStrategy;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.MatchResponse1 AonawareDictClient.DictServiceReference.DictServiceHttpPost.Match(AonawareDictClient.DictServiceReference.MatchRequest1 request) {
            return base.Channel.Match(request);
        }
        
        public DictionaryWord[] Match(string word, string strategy) {
            AonawareDictClient.DictServiceReference.MatchRequest1 inValue = new AonawareDictClient.DictServiceReference.MatchRequest1();
            inValue.word = word;
            inValue.strategy = strategy;
            AonawareDictClient.DictServiceReference.MatchResponse1 retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpPost)(this)).Match(inValue);
            return retVal.ArrayOfDictionaryWord;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AonawareDictClient.DictServiceReference.MatchInDictResponse1 AonawareDictClient.DictServiceReference.DictServiceHttpPost.MatchInDict(AonawareDictClient.DictServiceReference.MatchInDictRequest1 request) {
            return base.Channel.MatchInDict(request);
        }
        
        public DictionaryWord[] MatchInDict(string dictId, string word, string strategy) {
            AonawareDictClient.DictServiceReference.MatchInDictRequest1 inValue = new AonawareDictClient.DictServiceReference.MatchInDictRequest1();
            inValue.dictId = dictId;
            inValue.word = word;
            inValue.strategy = strategy;
            AonawareDictClient.DictServiceReference.MatchInDictResponse1 retVal = ((AonawareDictClient.DictServiceReference.DictServiceHttpPost)(this)).MatchInDict(inValue);
            return retVal.ArrayOfDictionaryWord;
        }
    }
}
