//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowMyIPClient.MyIp.Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.showmyip.com/soap2008/lookup/", ConfigurationName="MyIp.Reference.callshowmyip_lookupPortType")]
    public interface callshowmyip_lookupPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.showmyip.com/soap2008/lookupserver.php/callshowmyip_lookup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ShowMyIPClient.MyIp.Reference.IP_Address_Lookup_Properties callshowmyip_lookup(string lookup_ip, string lookup_host, string lookup_iplong, string optional_language_code, string optional_subscription_key, string optional_get_field_names, string optional_lookup_options);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.showmyip.com/soap2008/lookup/")]
    public partial class IP_Address_Lookup_Properties : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ipField;
        
        private string hOSTField;
        
        private string cOUNTRYField;
        
        private string cOUNTRY_CODE3Field;
        
        private string sTATEField;
        
        private string cITYField;
        
        private string iSPField;
        
        private string oRGField;
        
        private string dATETIME_STAMPField;
        
        private string tIMESERVER_STAMPField;
        
        private string vERSIONField;
        
        private string cOMMENTSField;
        
        private string cURRENCY_CODEField;
        
        private string cURRENCY_NAMEField;
        
        private string cONTINENTField;
        
        private string nATIONALITYField;
        
        private string aREA_CODEField;
        
        private string pOSTAL_ZIP_CODEField;
        
        private string dMA_CODEField;
        
        private string lATITUDEField;
        
        private string lONGITUDEField;
        
        private string tIMEZONEField;
        
        private string tOR_DETECTIONField;
        
        private string rBL_DNSBL_STATUSField;
        
        /// <remarks/>
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("IP");
            }
        }
        
        /// <remarks/>
        public string HOST {
            get {
                return this.hOSTField;
            }
            set {
                this.hOSTField = value;
                this.RaisePropertyChanged("HOST");
            }
        }
        
        /// <remarks/>
        public string COUNTRY {
            get {
                return this.cOUNTRYField;
            }
            set {
                this.cOUNTRYField = value;
                this.RaisePropertyChanged("COUNTRY");
            }
        }
        
        /// <remarks/>
        public string COUNTRY_CODE3 {
            get {
                return this.cOUNTRY_CODE3Field;
            }
            set {
                this.cOUNTRY_CODE3Field = value;
                this.RaisePropertyChanged("COUNTRY_CODE3");
            }
        }
        
        /// <remarks/>
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
                this.RaisePropertyChanged("STATE");
            }
        }
        
        /// <remarks/>
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
                this.RaisePropertyChanged("CITY");
            }
        }
        
        /// <remarks/>
        public string ISP {
            get {
                return this.iSPField;
            }
            set {
                this.iSPField = value;
                this.RaisePropertyChanged("ISP");
            }
        }
        
        /// <remarks/>
        public string ORG {
            get {
                return this.oRGField;
            }
            set {
                this.oRGField = value;
                this.RaisePropertyChanged("ORG");
            }
        }
        
        /// <remarks/>
        public string DATETIME_STAMP {
            get {
                return this.dATETIME_STAMPField;
            }
            set {
                this.dATETIME_STAMPField = value;
                this.RaisePropertyChanged("DATETIME_STAMP");
            }
        }
        
        /// <remarks/>
        public string TIMESERVER_STAMP {
            get {
                return this.tIMESERVER_STAMPField;
            }
            set {
                this.tIMESERVER_STAMPField = value;
                this.RaisePropertyChanged("TIMESERVER_STAMP");
            }
        }
        
        /// <remarks/>
        public string VERSION {
            get {
                return this.vERSIONField;
            }
            set {
                this.vERSIONField = value;
                this.RaisePropertyChanged("VERSION");
            }
        }
        
        /// <remarks/>
        public string COMMENTS {
            get {
                return this.cOMMENTSField;
            }
            set {
                this.cOMMENTSField = value;
                this.RaisePropertyChanged("COMMENTS");
            }
        }
        
        /// <remarks/>
        public string CURRENCY_CODE {
            get {
                return this.cURRENCY_CODEField;
            }
            set {
                this.cURRENCY_CODEField = value;
                this.RaisePropertyChanged("CURRENCY_CODE");
            }
        }
        
        /// <remarks/>
        public string CURRENCY_NAME {
            get {
                return this.cURRENCY_NAMEField;
            }
            set {
                this.cURRENCY_NAMEField = value;
                this.RaisePropertyChanged("CURRENCY_NAME");
            }
        }
        
        /// <remarks/>
        public string CONTINENT {
            get {
                return this.cONTINENTField;
            }
            set {
                this.cONTINENTField = value;
                this.RaisePropertyChanged("CONTINENT");
            }
        }
        
        /// <remarks/>
        public string NATIONALITY {
            get {
                return this.nATIONALITYField;
            }
            set {
                this.nATIONALITYField = value;
                this.RaisePropertyChanged("NATIONALITY");
            }
        }
        
        /// <remarks/>
        public string AREA_CODE {
            get {
                return this.aREA_CODEField;
            }
            set {
                this.aREA_CODEField = value;
                this.RaisePropertyChanged("AREA_CODE");
            }
        }
        
        /// <remarks/>
        public string POSTAL_ZIP_CODE {
            get {
                return this.pOSTAL_ZIP_CODEField;
            }
            set {
                this.pOSTAL_ZIP_CODEField = value;
                this.RaisePropertyChanged("POSTAL_ZIP_CODE");
            }
        }
        
        /// <remarks/>
        public string DMA_CODE {
            get {
                return this.dMA_CODEField;
            }
            set {
                this.dMA_CODEField = value;
                this.RaisePropertyChanged("DMA_CODE");
            }
        }
        
        /// <remarks/>
        public string LATITUDE {
            get {
                return this.lATITUDEField;
            }
            set {
                this.lATITUDEField = value;
                this.RaisePropertyChanged("LATITUDE");
            }
        }
        
        /// <remarks/>
        public string LONGITUDE {
            get {
                return this.lONGITUDEField;
            }
            set {
                this.lONGITUDEField = value;
                this.RaisePropertyChanged("LONGITUDE");
            }
        }
        
        /// <remarks/>
        public string TIMEZONE {
            get {
                return this.tIMEZONEField;
            }
            set {
                this.tIMEZONEField = value;
                this.RaisePropertyChanged("TIMEZONE");
            }
        }
        
        /// <remarks/>
        public string TOR_DETECTION {
            get {
                return this.tOR_DETECTIONField;
            }
            set {
                this.tOR_DETECTIONField = value;
                this.RaisePropertyChanged("TOR_DETECTION");
            }
        }
        
        /// <remarks/>
        public string RBL_DNSBL_STATUS {
            get {
                return this.rBL_DNSBL_STATUSField;
            }
            set {
                this.rBL_DNSBL_STATUSField = value;
                this.RaisePropertyChanged("RBL_DNSBL_STATUS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface callshowmyip_lookupPortTypeChannel : ShowMyIPClient.MyIp.Reference.callshowmyip_lookupPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class callshowmyip_lookupPortTypeClient : System.ServiceModel.ClientBase<ShowMyIPClient.MyIp.Reference.callshowmyip_lookupPortType>, ShowMyIPClient.MyIp.Reference.callshowmyip_lookupPortType {
        
        public callshowmyip_lookupPortTypeClient() {
        }
        
        public callshowmyip_lookupPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public callshowmyip_lookupPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public callshowmyip_lookupPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public callshowmyip_lookupPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShowMyIPClient.MyIp.Reference.IP_Address_Lookup_Properties callshowmyip_lookup(string lookup_ip, string lookup_host, string lookup_iplong, string optional_language_code, string optional_subscription_key, string optional_get_field_names, string optional_lookup_options) {
            return base.Channel.callshowmyip_lookup(lookup_ip, lookup_host, lookup_iplong, optional_language_code, optional_subscription_key, optional_get_field_names, optional_lookup_options);
        }
    }
}
