//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:GoogleSearch", ConfigurationName="ServiceReference1.GoogleSearchPort")]
    public interface GoogleSearchPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GoogleSearchAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        [return: System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        byte[] doGetCachedPage(string key, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GoogleSearchAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string doSpellingSuggestion(string key, string phrase);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GoogleSearchAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultElement))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GoogleClient.ServiceReference1.GoogleSearchResult doGoogleSearch(string key, string q, int start, int maxResults, bool filter, string restrict, bool safeSearch, string lr, string ie, string oe);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GoogleSearch")]
    public partial class GoogleSearchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool documentFilteringField;
        
        private string searchCommentsField;
        
        private int estimatedTotalResultsCountField;
        
        private bool estimateIsExactField;
        
        private ResultElement[] resultElementsField;
        
        private string searchQueryField;
        
        private int startIndexField;
        
        private int endIndexField;
        
        private string searchTipsField;
        
        private DirectoryCategory[] directoryCategoriesField;
        
        private double searchTimeField;
        
        /// <remarks/>
        public bool documentFiltering {
            get {
                return this.documentFilteringField;
            }
            set {
                this.documentFilteringField = value;
                this.RaisePropertyChanged("documentFiltering");
            }
        }
        
        /// <remarks/>
        public string searchComments {
            get {
                return this.searchCommentsField;
            }
            set {
                this.searchCommentsField = value;
                this.RaisePropertyChanged("searchComments");
            }
        }
        
        /// <remarks/>
        public int estimatedTotalResultsCount {
            get {
                return this.estimatedTotalResultsCountField;
            }
            set {
                this.estimatedTotalResultsCountField = value;
                this.RaisePropertyChanged("estimatedTotalResultsCount");
            }
        }
        
        /// <remarks/>
        public bool estimateIsExact {
            get {
                return this.estimateIsExactField;
            }
            set {
                this.estimateIsExactField = value;
                this.RaisePropertyChanged("estimateIsExact");
            }
        }
        
        /// <remarks/>
        public ResultElement[] resultElements {
            get {
                return this.resultElementsField;
            }
            set {
                this.resultElementsField = value;
                this.RaisePropertyChanged("resultElements");
            }
        }
        
        /// <remarks/>
        public string searchQuery {
            get {
                return this.searchQueryField;
            }
            set {
                this.searchQueryField = value;
                this.RaisePropertyChanged("searchQuery");
            }
        }
        
        /// <remarks/>
        public int startIndex {
            get {
                return this.startIndexField;
            }
            set {
                this.startIndexField = value;
                this.RaisePropertyChanged("startIndex");
            }
        }
        
        /// <remarks/>
        public int endIndex {
            get {
                return this.endIndexField;
            }
            set {
                this.endIndexField = value;
                this.RaisePropertyChanged("endIndex");
            }
        }
        
        /// <remarks/>
        public string searchTips {
            get {
                return this.searchTipsField;
            }
            set {
                this.searchTipsField = value;
                this.RaisePropertyChanged("searchTips");
            }
        }
        
        /// <remarks/>
        public DirectoryCategory[] directoryCategories {
            get {
                return this.directoryCategoriesField;
            }
            set {
                this.directoryCategoriesField = value;
                this.RaisePropertyChanged("directoryCategories");
            }
        }
        
        /// <remarks/>
        public double searchTime {
            get {
                return this.searchTimeField;
            }
            set {
                this.searchTimeField = value;
                this.RaisePropertyChanged("searchTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GoogleSearch")]
    public partial class ResultElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string summaryField;
        
        private string uRLField;
        
        private string snippetField;
        
        private string titleField;
        
        private string cachedSizeField;
        
        private bool relatedInformationPresentField;
        
        private string hostNameField;
        
        private DirectoryCategory directoryCategoryField;
        
        private string directoryTitleField;
        
        /// <remarks/>
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("summary");
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        public string snippet {
            get {
                return this.snippetField;
            }
            set {
                this.snippetField = value;
                this.RaisePropertyChanged("snippet");
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        public string cachedSize {
            get {
                return this.cachedSizeField;
            }
            set {
                this.cachedSizeField = value;
                this.RaisePropertyChanged("cachedSize");
            }
        }
        
        /// <remarks/>
        public bool relatedInformationPresent {
            get {
                return this.relatedInformationPresentField;
            }
            set {
                this.relatedInformationPresentField = value;
                this.RaisePropertyChanged("relatedInformationPresent");
            }
        }
        
        /// <remarks/>
        public string hostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
                this.RaisePropertyChanged("hostName");
            }
        }
        
        /// <remarks/>
        public DirectoryCategory directoryCategory {
            get {
                return this.directoryCategoryField;
            }
            set {
                this.directoryCategoryField = value;
                this.RaisePropertyChanged("directoryCategory");
            }
        }
        
        /// <remarks/>
        public string directoryTitle {
            get {
                return this.directoryTitleField;
            }
            set {
                this.directoryTitleField = value;
                this.RaisePropertyChanged("directoryTitle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:GoogleSearch")]
    public partial class DirectoryCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fullViewableNameField;
        
        private string specialEncodingField;
        
        /// <remarks/>
        public string fullViewableName {
            get {
                return this.fullViewableNameField;
            }
            set {
                this.fullViewableNameField = value;
                this.RaisePropertyChanged("fullViewableName");
            }
        }
        
        /// <remarks/>
        public string specialEncoding {
            get {
                return this.specialEncodingField;
            }
            set {
                this.specialEncodingField = value;
                this.RaisePropertyChanged("specialEncoding");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GoogleSearchPortChannel : GoogleClient.ServiceReference1.GoogleSearchPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GoogleSearchPortClient : System.ServiceModel.ClientBase<GoogleClient.ServiceReference1.GoogleSearchPort>, GoogleClient.ServiceReference1.GoogleSearchPort {
        
        public GoogleSearchPortClient() {
        }
        
        public GoogleSearchPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GoogleSearchPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoogleSearchPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoogleSearchPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] doGetCachedPage(string key, string url) {
            return base.Channel.doGetCachedPage(key, url);
        }
        
        public string doSpellingSuggestion(string key, string phrase) {
            return base.Channel.doSpellingSuggestion(key, phrase);
        }
        
        public GoogleClient.ServiceReference1.GoogleSearchResult doGoogleSearch(string key, string q, int start, int maxResults, bool filter, string restrict, bool safeSearch, string lr, string ie, string oe) {
            return base.Channel.doGoogleSearch(key, q, start, maxResults, filter, restrict, safeSearch, lr, ie, oe);
        }
    }
}
